package com.lizongying.mytv

import com.lizongying.mytv.models.ProgramType

object TVList {
    val list: Map<String, List<TV>> by lazy {
        setup()
    }

    private fun localIptv(title: String, alias: String = title) = TV(
        title = title,
        alias = alias,
        videoUrl = emptyList(),
        channel = "地方",
        logo = "",
        pid = "",
        sid = "",
        programType = ProgramType.IPTV,
        needToken = false,
        mustToken = false,
    )

    private fun setup(): Map<String, List<TV>> {
        val list = mapOf(
            "央视" to listOf(
                TV(
                    title = "CCTV1 综合",
                    alias = "CCTV1",
                    videoUrl = listOf(),
                    channel = "央视",
                    logo = "https://resources.yangshipin.cn/assets/oms/image/202306/d57905b93540bd15f0c48230dbbbff7ee0d645ff539e38866e2d15c8b9f7dfcd.png?imageMogr2/format/webp",
                    pid = "",
                    sid = "",
                    programType = ProgramType.IPTV,
                    needToken = false,
                    mustToken = false
                ),
                TV(
                    title = "CCTV2 财经",
                    alias = "CCTV2",
                    videoUrl = listOf(),
                    channel = "央视",
                    logo = "https://resources.yangshipin.cn/assets/oms/image/202306/20115388de0207131af17eac86c33049b95d69eaff064e55653a1b941810a006.png?imageMogr2/format/webp",
                    pid = "",
                    sid = "",
                    programType = ProgramType.IPTV,
                    needToken = false,
                    mustToken = false
                ),
                TV(
                    title = "CCTV3 综艺",
                    alias = "CCTV3",
                    videoUrl = listOf(),
                    channel = "央视",
                    logo = "https://resources.yangshipin.cn/assets/oms/image/202306/7b7a65c712450da3deb6ca66fbacf4f9aee00d3f20bd80eafb5ada01ec63eb3a.png?imageMogr2/format/webp",
                    pid = "",
                    sid = "",
                    programType = ProgramType.IPTV,
                    needToken = false,
                    mustToken = false
                ),
                TV(
                    title = "CCTV4 中文国际",
                    alias = "CCTV4",
                    videoUrl = listOf(),
                    channel = "央视",
                    logo = "https://resources.yangshipin.cn/assets/oms/image/202306/f357e58fdbcc076a3d65e1f958c942b2e14f14342c60736ceed98b092d35356a.png?imageMogr2/format/webp",
                    pid = "",
                    sid = "",
                    programType = ProgramType.IPTV,
                    needToken = false,
                    mustToken = false
                ),
                TV(
                    title = "CCTV5 体育",
                    alias = "CCTV5",
                    videoUrl = listOf(),
                    channel = "央视",
                    logo = "https://resources.yangshipin.cn/assets/oms/image/202306/0a6a7138952675983a3d854df7688557b286d59aa06166edae51506f9204d655.png?imageMogr2/format/webp",
                    pid = "",
                    sid = "",
                    programType = ProgramType.IPTV,
                    needToken = false,
                    mustToken = false
                ),
                TV(
                    title = "CCTV6 电影",
                    alias = "CCTV6",
                    videoUrl = listOf(),
                    channel = "央视",
                    logo = "https://resources.yangshipin.cn/assets/oms/image/202306/741515efda91f03f455df8a7da4ee11fa9329139c276435cf0a9e2af398d5bf2.png?imageMogr2/format/webp",
                    pid = "",
                    sid = "",
                    programType = ProgramType.IPTV,
                    needToken = false,
                    mustToken = false
                ),
                TV(
                    title = "CCTV7 国防军事",
                    alias = "CCTV7",
                    videoUrl = listOf(),
                    channel = "央视",
                    logo = "https://resources.yangshipin.cn/assets/oms/image/202306/b29af94e295ebdf646cefb68122c429b9cd921f498ca20d2d8070252536f9ff9.png?imageMogr2/format/webp",
                    pid = "",
                    sid = "",
                    programType = ProgramType.IPTV,
                    needToken = false,
                    mustToken = false
                ),
                TV(
                    title = "CCTV8 电视剧",
                    alias = "CCTV8",
                    videoUrl = listOf(),
                    channel = "央视",
                    logo = "https://resources.yangshipin.cn/assets/oms/image/202306/ad51de94426a0ba039e6dd6a8534ea98ecc813a6176bde87b4f18cc34d6d7590.png?imageMogr2/format/webp",
                    pid = "",
                    sid = "",
                    programType = ProgramType.IPTV,
                    needToken = false,
                    mustToken = false
                ),
                TV(
                    title = "CCTV9 纪录",
                    alias = "CCTV9",
                    videoUrl = listOf(),
                    channel = "央视",
                    logo = "https://resources.yangshipin.cn/assets/oms/image/202306/2ed1b4deeca179d5db806bb941790f82eb92a1b7299c1c38fe027f95a5caee5e.png?imageMogr2/format/webp",
                    pid = "",
                    sid = "",
                    programType = ProgramType.IPTV,
                    needToken = false,
                    mustToken = false
                ),
                TV(
                    title = "CCTV10 科教",
                    alias = "CCTV10",
                    videoUrl = listOf(),
                    channel = "央视",
                    logo = "https://resources.yangshipin.cn/assets/oms/image/202306/aa6157ec65188cd41826e5a2f088c3d6d153205f5f6428258d12c59999e221aa.png?imageMogr2/format/webp",
                    pid = "",
                    sid = "",
                    programType = ProgramType.IPTV,
                    needToken = false,
                    mustToken = false
                ),
                TV(
                    title = "CCTV11 戏曲",
                    alias = "CCTV11",
                    videoUrl = listOf(),
                    channel = "央视",
                    logo = "https://resources.yangshipin.cn/assets/oms/image/202306/ed12ed7c7a1034dae4350011fe039284c5d5a836506b28c9e32e3c75299625c0.png?imageMogr2/format/webp",
                    pid = "",
                    sid = "",
                    programType = ProgramType.IPTV,
                    needToken = false,
                    mustToken = false
                ),
                TV(
                    title = "CCTV12 社会与法",
                    alias = "CCTV12",
                    videoUrl = listOf(),
                    channel = "央视",
                    logo = "https://resources.yangshipin.cn/assets/oms/image/202306/484083cffaa40df7e659565e8cb4d1cc740158a185512114167aa21fa0c59240.png?imageMogr2/format/webp",
                    pid = "",
                    sid = "",
                    programType = ProgramType.IPTV,
                    needToken = false,
                    mustToken = false
                ),
                TV(
                    title = "CCTV13 新闻",
                    alias = "CCTV13",
                    videoUrl = listOf(),
                    channel = "央视",
                    logo = "https://resources.yangshipin.cn/assets/oms/image/202306/266da7b43c03e2312186b4a999e0f060e8f15b10d2cc2c9aa32171819254cf1a.png?imageMogr2/format/webp",
                    pid = "",
                    sid = "",
                    programType = ProgramType.IPTV,
                    needToken = false,
                    mustToken = false
                ),
                TV(
                    title = "CCTV14 少儿",
                    alias = "CCTV14",
                    videoUrl = listOf(),
                    channel = "央视",
                    logo = "https://resources.yangshipin.cn/assets/oms/image/202306/af6b603896938dc346fbb16abfc63c12cba54b0ec9d18770a15d347d115f12d5.png?imageMogr2/format/webp",
                    pid = "",
                    sid = "",
                    programType = ProgramType.IPTV,
                    needToken = false,
                    mustToken = false
                ),
                TV(
                    title = "CCTV15 音乐",
                    alias = "CCTV15",
                    videoUrl = listOf(),
                    channel = "央视",
                    logo = "https://resources.yangshipin.cn/assets/oms/image/202306/2ceee92188ef684efe0d8b90839c4f3ad450d179dc64d59beff417059453af47.png?imageMogr2/format/webp",
                    pid = "",
                    sid = "",
                    programType = ProgramType.IPTV,
                    needToken = false,
                    mustToken = false
                ),
                TV(
                    title = "CCTV16 奥林匹克",
                    alias = "CCTV16",
                    videoUrl = listOf(),
                    channel = "央视",
                    logo = "https://resources.yangshipin.cn/assets/oms/image/202306/53793fa7bacd3a93ff6dc5d2758418985e1f952a316c335d663b572d8bdcd74d.png?imageMogr2/format/webp",
                    pid = "",
                    sid = "",
                    programType = ProgramType.IPTV,
                    needToken = false,
                    mustToken = false
                ),
                TV(
                    title = "CCTV17 农业农村",
                    alias = "CCTV17",
                    videoUrl = listOf(),
                    channel = "央视",
                    logo = "https://resources.yangshipin.cn/assets/oms/image/202306/ddef563072f8bad2bea5b9e52674cb7b4ed50efb20c26e61994dfbdf05c1e3c0.png?imageMogr2/format/webp",
                    pid = "",
                    sid = "",
                    programType = ProgramType.IPTV,
                    needToken = false,
                    mustToken = false
                ),
                TV(
                    title = "CCTV5+ 体育赛事",
                    alias = "CCTV5+",
                    videoUrl = listOf(),
                    channel = "央视",
                    logo = "https://resources.yangshipin.cn/assets/oms/image/202306/649ad76a90bfef55b05db9fe52e006487280f619089099d5dc971e387fc6eff0.png?imageMogr2/format/webp",
                    pid = "",
                    sid = "",
                    programType = ProgramType.IPTV,
                    needToken = false,
                    mustToken = false
                ),
                TV(
                    title = "CCTV4K 超高清",
                    alias = "CCTV4K",
                    videoUrl = listOf(),
                    channel = "央视",
                    logo = "https://resources.yangshipin.cn/assets/oms/image/202306/3e9d06fd7244d950df5838750f1c6ac3456e172b51caca2c16d2282125b111e8.png?imageMogr2/format/webp",
                    pid = "",
                    sid = "",
                    programType = ProgramType.IPTV,
                    needToken = false,
                    mustToken = false
                ),
                TV(
                    title = "CCTV8K 超高清",
                    alias = "CCTV8K",
                    videoUrl = listOf(),
                    channel = "央视",
                    logo = R.drawable.cctv8k,
                    pid = "",
                    sid = "",
                    programType = ProgramType.IPTV,
                    needToken = false,
                    mustToken = false
                ),
                TV(
                    title = "风云剧场",
                    alias = "CCTV风云剧场",
                    videoUrl = listOf(),
                    channel = "央视",
                    logo = "https://resources.yangshipin.cn/assets/oms/image/202306/4d549e53e6d0f632d5a633d1945280797b153e588f919221a07faa869812cc89.png?imageMogr2/format/webp",
                    pid = "",
                    sid = "",
                    programType = ProgramType.IPTV,
                    needToken = false,
                    mustToken = false
                ),
                TV(
                    title = "第一剧场",
                    alias = "CCTV第一剧场",
                    videoUrl = listOf(),
                    channel = "央视",
                    logo = "https://resources.yangshipin.cn/assets/oms/image/202306/a556bd7d93ce65e18f243a8892b5604f4faa994a4897315914216a710a706208.png?imageMogr2/format/webp",
                    pid = "",
                    sid = "",
                    programType = ProgramType.IPTV,
                    needToken = false,
                    mustToken = false
                ),
                TV(
                    title = "怀旧剧场",
                    alias = "CCTV怀旧剧场",
                    videoUrl = listOf(),
                    channel = "央视",
                    logo = "https://resources.yangshipin.cn/assets/oms/image/202306/5661bd04fecdb6e899f801147a22ab5d3a475bf2b62e30aec2c0023190ebc9b1.png?imageMogr2/format/webp",
                    pid = "",
                    sid = "",
                    programType = ProgramType.IPTV,
                    needToken = false,
                    mustToken = false
                ),
                TV(
                    title = "世界地理",
                    alias = "CCTV世界地理",
                    videoUrl = listOf(),
                    channel = "央视",
                    logo = "https://resources.yangshipin.cn/assets/oms/image/202306/bb3c6c9e145d698137f5bb64a582021a01b51344b929003630eb769ea65832a9.png?imageMogr2/format/webp",
                    pid = "",
                    sid = "",
                    programType = ProgramType.IPTV,
                    needToken = false,
                    mustToken = false
                ),
                TV(
                    title = "风云音乐",
                    alias = "CCTV风云音乐",
                    videoUrl = listOf(),
                    channel = "央视",
                    logo = "https://resources.yangshipin.cn/assets/oms/image/202306/bbf1d024c5228b8dd128b0e3cb1717d173fab4ee84c3a4c8a57b1a215362ca3b.png?imageMogr2/format/webp",
                    pid = "",
                    sid = "",
                    programType = ProgramType.IPTV,
                    needToken = false,
                    mustToken = false
                ),
                TV(
                    title = "兵器科技",
                    alias = "CCTV兵器科技",
                    videoUrl = listOf(),
                    channel = "央视",
                    logo = "https://resources.yangshipin.cn/assets/oms/image/202306/4c6b6a6d3839889f34d33db3c2f80233b26b74d3489b393487635f8704e70796.png?imageMogr2/format/webp",
                    pid = "",
                    sid = "",
                    programType = ProgramType.IPTV,
                    needToken = false,
                    mustToken = false
                ),
                TV(
                    title = "风云足球",
                    alias = "CCTV风云足球",
                    videoUrl = listOf(),
                    channel = "央视",
                    logo = "https://resources.yangshipin.cn/assets/oms/image/202306/cd1e2bb52b06a991de168733e5ff0f1d85adc8042d40c8f393f723543e5dd08a.png?imageMogr2/format/webp",
                    pid = "",
                    sid = "",
                    programType = ProgramType.IPTV,
                    needToken = false,
                    mustToken = false
                ),
                TV(
                    title = "高尔夫网球",
                    alias = "CCTV高尔夫网球",
                    videoUrl = listOf(),
                    channel = "央视",
                    logo = "https://resources.yangshipin.cn/assets/oms/image/202306/cdd1b31ede7a5ad049ed53d9a072422f829e72dd062ed2c19e077fdd01699071.png?imageMogr2/format/webp",
                    pid = "",
                    sid = "",
                    programType = ProgramType.IPTV,
                    needToken = false,
                    mustToken = false
                ),
                TV(
                    title = "女性时尚",
                    alias = "CCTV女性时尚",
                    videoUrl = listOf(),
                    channel = "央视",
                    logo = "https://resources.yangshipin.cn/assets/oms/image/202306/fa28955ce8b2539d728bf4c6a13a46ff57ad76eae46627f7bcfb1ed8a613d3fc.png?imageMogr2/format/webp",
                    pid = "",
                    sid = "",
                    programType = ProgramType.IPTV,
                    needToken = false,
                    mustToken = false
                ),
                TV(
                    title = "央视文化精品",
                    alias = "CCTV文化精品",
                    videoUrl = listOf(),
                    channel = "央视",
                    logo = "https://resources.yangshipin.cn/assets/oms/image/202306/14ac5ce40482cacd3d4b37435222bfe86af2b452a2f04ecbfc1d13d76edd7c57.png?imageMogr2/format/webp",
                    pid = "",
                    sid = "",
                    programType = ProgramType.IPTV,
                    needToken = false,
                    mustToken = false
                ),
                TV(
                    title = "央视台球",
                    alias = "CCTV台球",
                    videoUrl = listOf(),
                    channel = "央视",
                    logo = "https://resources.yangshipin.cn/assets/oms/image/202306/10e14a92478011aa6c3c8562e62127f3b1908e29fcd78e4b2b24b9e6d3ec2fbc.png?imageMogr2/format/webp",
                    pid = "",
                    sid = "",
                    programType = ProgramType.IPTV,
                    needToken = false,
                    mustToken = false
                ),
                TV(
                    title = "电视指南",
                    alias = "CCTV电视指南",
                    videoUrl = listOf(),
                    channel = "央视",
                    logo = "https://resources.yangshipin.cn/assets/oms/image/202306/244d72c0eb1615ed7d51c2f5db5a67f306aa3f58c05bc2d34de3aa7e956dc8c9.png?imageMogr2/format/webp",
                    pid = "",
                    sid = "",
                    programType = ProgramType.IPTV,
                    needToken = false,
                    mustToken = false
                ),
                TV(
                    title = "卫生健康",
                    alias = "CCTV卫生健康",
                    videoUrl = listOf(),
                    channel = "央视",
                    logo = "https://resources.yangshipin.cn/assets/oms/image/202306/54a6863656fdfd8f803be193ddf22441c5000a108833889816fd2d8911715ce8.png?imageMogr2/format/webp",
                    pid = "",
                    sid = "",
                    programType = ProgramType.IPTV,
                    needToken = false,
                    mustToken = false
                ),
            ),
            "地方" to listOf(
                TV(
                    title = "东方卫视",
                    alias = "东方卫视",
                    videoUrl = listOf(),
                    channel = "地方",
                    logo = "https://resources.yangshipin.cn/assets/oms/image/202306/9bd372ca292a82ce3aa08772b07efc4af1f85c21d1f268ea33440c49e9a0a488.png?imageMogr2/format/webp",
                    pid = "",
                    sid = "",
                    programType = ProgramType.IPTV,
                    needToken = false,
                    mustToken = false
                ),
                TV(
                    title = "湖南卫视",
                    alias = "湖南卫视",
                    videoUrl = listOf(),
                    channel = "地方",
                    logo = "https://resources.yangshipin.cn/assets/oms/image/202306/4120e89d3079d08aa17d382f69a2308ec70839b278367763c34a34666c75cb88.png?imageMogr2/format/webp",
                    pid = "",
                    sid = "",
                    programType = ProgramType.IPTV,
                    needToken = false,
                    mustToken = false
                ),
                TV(
                    title = "湖北卫视",
                    alias = "湖北卫视",
                    videoUrl = listOf(),
                    channel = "地方",
                    logo = "https://resources.yangshipin.cn/assets/oms/image/202306/7a6be5a2bb1dc53a945c016ff1f525dc4a84c51db371c15c89aa55404b0ba784.png?imageMogr2/format/webp",
                    pid = "",
                    sid = "",
                    programType = ProgramType.IPTV,
                    needToken = false,
                    mustToken = false
                ),
                TV(
                    title = "辽宁卫视",
                    alias = "辽宁卫视",
                    videoUrl = listOf(),
                    channel = "地方",
                    logo = "https://resources.yangshipin.cn/assets/oms/image/202306/ac4ed6058a87c101ae7147ebc38905d0cae047fb73fd277ee5049b84f52bda36.png?imageMogr2/format/webp",
                    pid = "",
                    sid = "",
                    programType = ProgramType.IPTV,
                    needToken = false,
                    mustToken = false
                ),
                TV(
                    title = "江苏卫视",
                    alias = "江苏卫视",
                    videoUrl = listOf(),
                    channel = "地方",
                    logo = "https://resources.yangshipin.cn/assets/oms/image/202306/380ad685c0c1d5b2c902246b8d2df6d3f9b45e2837abcfe493075bbded597a31.png?imageMogr2/format/webp",
                    pid = "",
                    sid = "",
                    programType = ProgramType.IPTV,
                    needToken = false,
                    mustToken = false
                ),
                TV(
                    title = "江西卫视",
                    alias = "江西卫视",
                    videoUrl = listOf(),
                    channel = "地方",
                    logo = "https://resources.yangshipin.cn/assets/oms/image/202306/3c760d0d00463855890e8a1864ea4a6b6dd66b90c29b4ac714a4b17c16519871.png?imageMogr2/format/webp",
                    pid = "",
                    sid = "",
                    programType = ProgramType.IPTV,
                    needToken = false,
                    mustToken = false
                ),
                TV(
                    title = "山东卫视",
                    alias = "山东卫视",
                    videoUrl = listOf(),
                    channel = "地方",
                    logo = "https://resources.yangshipin.cn/assets/oms/image/202306/22d403f07a7cf5410b3ad3ddb65a11aa229a32475fac213f5344c9f0ec330ca1.png?imageMogr2/format/webp",
                    pid = "",
                    sid = "",
                    programType = ProgramType.IPTV,
                    needToken = false,
                    mustToken = false
                ),
                TV(
                    title = "广东卫视",
                    alias = "广东卫视",
                    videoUrl = listOf(),
                    channel = "地方",
                    logo = "https://resources.yangshipin.cn/assets/oms/image/202306/28886880a4dc0f06fb7e0a528a1def0591d61a65870e29176ede0cc92033bbfd.png?imageMogr2/format/webp",
                    pid = "",
                    sid = "",
                    programType = ProgramType.IPTV,
                    needToken = false,
                    mustToken = false
                ),
                TV(
                    title = "广西卫视",
                    alias = "广西卫视",
                    videoUrl = listOf(),
                    channel = "地方",
                    logo = "https://resources.yangshipin.cn/assets/oms/image/202306/54b7e97cb816bb223fe05f3fc44da2c7820eb66e8550c19d23100f2c414ecc38.png?imageMogr2/format/webp",
                    pid = "",
                    sid = "",
                    programType = ProgramType.IPTV,
                    needToken = false,
                    mustToken = false
                ),
                TV(
                    title = "重庆卫视",
                    alias = "重庆卫视",
                    videoUrl = listOf(),
                    channel = "地方",
                    logo = R.drawable.chongqing,
                    pid = "",
                    sid = "",
                    programType = ProgramType.IPTV,
                    needToken = false,
                    mustToken = false
                ),
                TV(
                    title = "河南卫视",
                    alias = "河南卫视",
                    videoUrl = listOf(),
                    channel = "地方",
                    logo = "https://resources.yangshipin.cn/assets/oms/image/202306/74925962148a6d31c85808b6cd4e444c2a54bab393d2c5fc85e960b50e22fa86.png?imageMogr2/format/webp",
                    pid = "",
                    sid = "",
                    programType = ProgramType.IPTV,
                    needToken = false,
                    mustToken = false
                ),
                TV(
                    title = "河北卫视",
                    alias = "河北卫视",
                    videoUrl = listOf(),
                    channel = "地方",
                    logo = "https://resources.yangshipin.cn/assets/oms/image/202306/d545becdc81c60197b08c7f47380705e4665ed3fe55efc8b855e486f6e655378.png?imageMogr2/format/webp",
                    pid = "",
                    sid = "",
                    programType = ProgramType.IPTV,
                    needToken = false,
                    mustToken = false
                ),
                TV(
                    title = "贵州卫视",
                    alias = "贵州卫视",
                    videoUrl = listOf(),
                    channel = "地方",
                    logo = "https://resources.yangshipin.cn/assets/oms/image/202306/4eb45f4781d33d872af027dc01c941559aab55667dd99cc5c22bef7037807b13.png?imageMogr2/format/webp",
                    pid = "",
                    sid = "",
                    programType = ProgramType.IPTV,
                    needToken = false,
                    mustToken = false
                ),
                TV(
                    title = "北京卫视",
                    alias = "北京卫视",
                    videoUrl = listOf(),
                    channel = "地方",
                    logo = "https://resources.yangshipin.cn/assets/oms/image/202306/f4f23633c578beea49a3841d88d3490100f029ee349059fa532869db889872c5.png?imageMogr2/format/webp",
                    pid = "",
                    sid = "",
                    programType = ProgramType.IPTV,
                    needToken = false,
                    mustToken = false
                ),
                TV(
                    title = "黑龙江卫视",
                    alias = "黑龙江卫视",
                    videoUrl = listOf(),
                    channel = "地方",
                    logo = "https://resources.yangshipin.cn/assets/oms/image/202306/d8273ae9be698ce2db21f5b886ecac95a73429593f93713c60ed8c12c38bf0d3.png?imageMogr2/format/webp",
                    pid = "",
                    sid = "",
                    programType = ProgramType.IPTV,
                    needToken = false,
                    mustToken = false
                ),
                TV(
                    title = "浙江卫视",
                    alias = "浙江卫视",
                    videoUrl = listOf(),
                    channel = "地方",
                    logo = "https://resources.yangshipin.cn/assets/oms/image/202306/a66c836bd98ba3e41a2e9a570d4b9c50dedc6839e9de333e2e78212ad505f37e.png?imageMogr2/format/webp",
                    pid = "",
                    sid = "",
                    programType = ProgramType.IPTV,
                    needToken = false,
                    mustToken = false
                ),
                TV(
                    title = "安徽卫视",
                    alias = "安徽卫视",
                    videoUrl = listOf(),
                    channel = "地方",
                    logo = "https://resources.yangshipin.cn/assets/oms/image/202306/f35fa04b51b1ee4984b03578b65403570868ebca03c6c01e11b097f999a58d9b.png?imageMogr2/format/webp",
                    pid = "",
                    sid = "",
                    programType = ProgramType.IPTV,
                    needToken = false,
                    mustToken = false
                ),
                TV(
                    title = "深圳卫视",
                    alias = "深圳卫视",
                    videoUrl = listOf(),
                    channel = "地方",
                    logo = "https://resources.yangshipin.cn/assets/oms/image/202306/d59fec04c902e3581c617136d02d4b9b8c4cbe64272781ddd3525e80c823edb7.png?imageMogr2/format/webp",
                    pid = "",
                    sid = "",
                    programType = ProgramType.IPTV,
                    needToken = false,
                    mustToken = false
                ),
                TV(
                    title = "四川卫视",
                    alias = "四川卫视",
                    videoUrl = listOf(),
                    channel = "地方",
                    logo = "https://resources.yangshipin.cn/assets/oms/image/202306/3276a414ae0eaa0f116f2045cd913367967d0c7c1e978e8621ac3879436c6ed7.png?imageMogr2/format/webp",
                    pid = "",
                    sid = "",
                    programType = ProgramType.IPTV,
                    needToken = false,
                    mustToken = false
                ),
                TV(
                    title = "东南卫视",
                    alias = "东南卫视",
                    videoUrl = listOf(),
                    channel = "地方",
                    logo = "https://resources.yangshipin.cn/assets/oms/image/202306/3208fe6564a293c21b711333fb3edb05bb5b406cff840573c9a8d839680a1579.png?imageMogr2/format/webp",
                    pid = "",
                    sid = "",
                    programType = ProgramType.IPTV,
                    needToken = false,
                    mustToken = false
                ),
                TV(
                    title = "海南卫视",
                    alias = "海南卫视",
                    videoUrl = listOf(),
                    channel = "地方",
                    logo = "https://resources.yangshipin.cn/assets/oms/image/202306/6e060391fde0469801fc3d84dbf204b4f8d650d251f17d7595a6964c0bb99e81.png?imageMogr2/format/webp",
                    pid = "",
                    sid = "",
                    programType = ProgramType.IPTV,
                    needToken = false,
                    mustToken = false
                ),
                TV(
                    title = "天津卫视",
                    alias = "天津卫视",
                    videoUrl = listOf(),
                    channel = "地方",
                    logo = R.drawable.tianjin,
                    pid = "",
                    sid = "",
                    programType = ProgramType.IPTV,
                    needToken = false,
                    mustToken = false
                ),
                TV(
                    title = "新疆卫视",
                    alias = "新疆卫视",
                    videoUrl = listOf(),
                    channel = "地方",
                    logo = R.drawable.xinjiang,
                    pid = "",
                    sid = "",
                    programType = ProgramType.IPTV,
                    needToken = false,
                    mustToken = false
                ),
                TV(
                    title = "兵团卫视",
                    alias = "兵团卫视",
                    videoUrl = listOf(),
                    channel = "地方",
                    logo = R.drawable.bingtuan,
                    pid = "",
                    sid = "",
                    programType = ProgramType.IPTV,
                    needToken = false,
                    mustToken = false
                ),
                localIptv("吉林卫视"),
                localIptv("云南卫视"),
                localIptv("陕西卫视"),
                localIptv("山西卫视"),
                localIptv("甘肃卫视"),
                localIptv("青海卫视"),
                localIptv("宁夏卫视"),
                localIptv("内蒙古卫视"),
                localIptv("西藏卫视"),
                localIptv("海峡卫视"),
                localIptv("厦门卫视"),
                localIptv("三沙卫视"),
                localIptv("大湾区卫视"),
                localIptv("延边卫视"),
                localIptv("康巴卫视"),
                localIptv("安多卫视"),
                localIptv("内蒙古蒙语卫视"),
                localIptv("农林卫视"),
                localIptv("山东教育卫视", "山东教育"),
                localIptv("金鹰卡通"),
                localIptv("卡酷少儿"),
                TV(
                    title = "CETV1",
                    alias = "CETV1",
                    videoUrl = listOf(),
                    channel = "地方",
                    logo = R.drawable.cetv1,
                    pid = "",
                    sid = "",
                    programType = ProgramType.IPTV,
                    needToken = false,
                    mustToken = false
                ),
            ),
            "港澳台" to listOf(
                TV(
                    title = "凤凰卫视资讯台",
                    alias = "凤凰资讯",
                    videoUrl = listOf(),
                    channel = "港澳台",
                    logo = "http://c1.fengshows-cdn.com/a/2021_22/79dcc3a9da358a3.png",
                    pid = "",
                    sid = "",
                    programType = ProgramType.IPTV,
                    needToken = false,
                    mustToken = false
                ),
                TV(
                    title = "凤凰卫视中文台",
                    alias = "凤凰中文",
                    videoUrl = listOf(),
                    channel = "港澳台",
                    logo = "http://c1.fengshows-cdn.com/a/2021_22/ede3d9e09be28e5.png",
                    pid = "",
                    sid = "",
                    programType = ProgramType.IPTV,
                    needToken = false,
                    mustToken = false
                ),
                TV(
                    title = "凤凰卫视香港台",
                    alias = "凤凰香港",
                    videoUrl = listOf(),
                    channel = "港澳台",
                    logo = "http://c1.fengshows-cdn.com/a/2021_23/325d941090bee17.png",
                    pid = "",
                    sid = "",
                    programType = ProgramType.IPTV,
                    needToken = false,
                    mustToken = false
                ),
            ),
            "国际" to listOf(
                TV(
                    title = "CGTN",
                    alias = "CGTN",
                    videoUrl = listOf(),
                    channel = "国际",
                    logo = "https://resources.yangshipin.cn/assets/oms/image/202306/a72dff758ca1c17cd0ecc8cedc11b893d208f409d5e6302faa0e9d298848abc3.png?imageMogr2/format/webp",
                    pid = "",
                    sid = "",
                    programType = ProgramType.IPTV,
                    needToken = false,
                    mustToken = false
                ),
                TV(
                    title = "CGTN 法语频道",
                    alias = "CGTN法语",
                    videoUrl = listOf(),
                    channel = "国际",
                    logo = "https://resources.yangshipin.cn/assets/oms/image/202306/a8d0046a47433d952bf6ed17062deb8bd2184ba9aec0f7781df6bf9487a3ffcf.png?imageMogr2/format/webp",
                    pid = "",
                    sid = "",
                    programType = ProgramType.IPTV,
                    needToken = false,
                    mustToken = false
                ),
                TV(
                    title = "CGTN 俄语频道",
                    alias = "CGTN俄语",
                    videoUrl = listOf(),
                    channel = "国际",
                    logo = "https://resources.yangshipin.cn/assets/oms/image/202306/bf0a820893cbaf20dd0333e27042e1ef9c8806e5b602b6a8c95af399db0bc77a.png?imageMogr2/format/webp",
                    pid = "",
                    sid = "",
                    programType = ProgramType.IPTV,
                    needToken = false,
                    mustToken = false
                ),
                TV(
                    title = "CGTN 阿拉伯语频道",
                    alias = "CGTN阿语",
                    videoUrl = listOf(),
                    channel = "国际",
                    logo = "https://resources.yangshipin.cn/assets/oms/image/202306/2e44e2aa3e7a1cedf07fd0ae59fe69e86a60a2632660a006e3e9e7397b2d107e.png?imageMogr2/format/webp",
                    pid = "",
                    sid = "",
                    programType = ProgramType.IPTV,
                    needToken = false,
                    mustToken = false
                ),
                TV(
                    title = "CGTN 西班牙语频道",
                    alias = "CGTN西语",
                    videoUrl = listOf(),
                    channel = "国际",
                    logo = "https://resources.yangshipin.cn/assets/oms/image/202309/7c337e3dbe64402ec7e4678a619a4a6d95144e42f35161181ff78e143b7cf67a.png?imageMogr2/format/webp",
                    pid = "",
                    sid = "",
                    programType = ProgramType.IPTV,
                    needToken = false,
                    mustToken = false
                ),
                TV(
                    title = "CGTN 纪录频道",
                    alias = "CGTN纪录",
                    videoUrl = listOf(),
                    channel = "国际",
                    logo = "https://resources.yangshipin.cn/assets/oms/image/202309/74d3ac436a7e374879578de1d87a941fbf566d39d5632b027c5097891ed32bd5.png?imageMogr2/format/webp",
                    pid = "",
                    sid = "",
                    programType = ProgramType.IPTV,
                    needToken = false,
                    mustToken = false
                ),
            )
        )

        // Assign sequential IDs to all channels (no more token filtering)
        val listNew = mutableMapOf<String, List<TV>>()
        var id = 0
        list.forEach { (k, v) ->
            val group = mutableListOf<TV>()
            v.filterNot { it.title in HIDDEN_UNPLAYABLE_CHANNELS }.forEach { v1 ->
                v1.id = id
                id++
                group.add(v1)
            }
            if (group.size > 0) {
                listNew[k] = group
            }
        }
        return listNew
    }

    /** Channels confirmed unavailable or consistently mismatched on the target tablet. */
    private val HIDDEN_UNPLAYABLE_CHANNELS = setOf(
        "CCTV4K 超高清",
        "CCTV8K 超高清",
        "风云剧场",
        "第一剧场",
        "怀旧剧场",
        "世界地理",
        "风云音乐",
        "兵器科技",
        "风云足球",
        "高尔夫网球",
        "女性时尚",
        "央视文化精品",
        "央视台球",
        "电视指南",
        "卫生健康",
        "凤凰卫视资讯台",
        "凤凰卫视中文台",
        "凤凰卫视香港台",
        "CETV1",
    )
}
